name: License Compliance

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  pull-requests: read
  contents: write

jobs:
  check_licences:
    uses: eclipse-ecsp/.github/.github/workflows/workflow-licences-analysis.yml@cd37031cbafcac029ce6cd8b98dba5c41e9531d6
    name: Analyse Licences
    with:
      java_version: '25'
      java_distribution: 'temurin'
      create-review: true
    secrets:
      token: ${{ secrets.GITLAB_API_TOKEN }}
