
name: Maven Build & Sonar Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  maven_build:
    uses: eclipse-ecsp/.github/.github/workflows/workflow-maven-run.yml@test-report
    name: Maven Build
    with:
      maven_args: 'clean package --file pom.xml'
      test_report: true
      summaries-test-report: true

    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  sonar_analysis:
    needs: maven_build
    uses: eclipse-ecsp/.github/.github/workflows/workflow-sonar-analysis.yml@main
    secrets:
      token: ${{ secrets.SONAR_TOKEN }}
  dependencies_update:
    needs: sonar_analysis
    uses: eclipse-ecsp/.github/.github/workflows/workflow-dependencies-update.yml@main
    secrets: inherit
    permissions:
      pull-requests: write
      contents: read

  docker_push_api_registry:
    needs: sonar_analysis
    if: false
    uses: eclipse-ecsp/.github/.github/workflows/workflow-docker-push.yml@main
    secrets: inherit
    with:
      context_path: ./api-registry
      maven_args: 'clean package --file pom.xml'

  docker_push_api-gateway:
    needs: sonar_analysis
    if: false
    uses: eclipse-ecsp/.github/.github/workflows/workflow-docker-push.yml@main
    secrets: inherit
    with:
      context_path: ./api-gateway
      maven_args: 'clean package --file pom.xml'
